server:
  port: 8088

# JasyptUtils
jasypt:
  encryptor:
    password: 7777777

spring:
  # DB
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.219.192.172:3306/doorkeeper?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: ENC(KNg4F1am9e6SudjCk4gsLg==)
      password: ENC(KNg4F1am9e6SudjCk4gsLg==)

eureka:
  client:
    service-url:
      defaultZone: http://10.219.192.172:8001/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: prod

