eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8000/eureka/
  server:
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 5000
  instance:
    prefer-ip-address: true

server:
  port: 8000
