jasypt:
  encryptor:
    password: 7777777

spring:
  # AuthcService的数据存储在这个库中
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://test.bbb.com:3306/haokailvye_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: ENC(/EvkGxk1UP8SmCFl446R6Q==) # JasyptUtils 和 jasypt.encryptor.password 加密值
      password: ENC(qnd7oyEIg8E4UAxiYHSaWFMri3TD6tTK)

# DAO层基于MyBatisPlus
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml

# 注册中心以nacos为例
dubbo:
  application:
    name: limbo-authc
  registry:
    address: your.nacos.host:8848
    protocol: nacos
    parameters:
      namespace: your-nacos-namespace
  provider:
    validation: true
    token: true
  service:
    version: 1.0.0

authc:
  project-api:
    # 调用ProjectApi时，需要验证认证密码，带有这个密码的才能访问。这个密码应该只下发给AuthcAdmin项目
    certificate: 123567890