server:
  port: 8088

# JasyptUtils
jasypt:
  encryptor:
    password: 7777777

# 配置 https://springdoc.org/#springdoc-openapi-core-properties
# 注解 https://springdoc.org/#migrating-from-springfox
# 访问 http://localhost:8088/api-docs.html
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  group-configs:
    - group: doorkeeper-server
      pathsToMatch: /**

spring:
  # DB
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/doorkeeper?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: ENC(KNg4F1am9e6SudjCk4gsLg==)
      password: ENC(KNg4F1am9e6SudjCk4gsLg==)

# DAO层基于MyBatisPlus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: dev
