spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: doorkeeper-server

# 配置 https://springdoc.org/#springdoc-openapi-core-properties
# 注解 https://springdoc.org/#migrating-from-springfox
# 访问 http://localhost:8088/api-docs.html
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  group-configs:
    - group: doorkeeper-server
      pathsToMatch: /**

# DAO层基于MyBatisPlus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# log
logging:
  config: classpath:log4j2.xml