# nacos 作为配置中心 注册中心
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 172.17.16.9:8848
    namespace: da31431c-2dc3-4705-a875-a17f8eb27f55
    data-id: admin
    group: limbo-authc
    type: yaml

dubbo:
  application:
    name: limbo-authc
  registry:
    address: ${nacos.config.server-addr}
    protocol: nacos
    parameters:
      namespace: ${nacos.config.namespace}
  consumer:
    mock: true
    timeout: 3000
  service:
    version: 1.0.0